name:                baz
version:             0.1.0.0
github:              "Hexirp/baz"
license:             BSD3
author:              "Hexirp"
maintainer:          "Hexirp@users.noreply.github.com"
copyright:           "2018 Hexirp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Other

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Hexirp/baz#readme>

dependencies:
- base >= 4.7 && < 5
- rio

library:
  source-dirs: src

executables:
  baz-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - baz

tests:
  baz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - baz
